application: visi-bull
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Serve CSS files from their page directory.
- url: /static/(.*\.css)
  static_files: pages/\1
  upload: pages/(.*\.css)
  mime_type: text/css

# Serve D3 from the static directory.
- url: /static/(.*d3.min.js)
  static_files: static/\1
  upload: /static/(.*d3.min.js)
  mime_type: text/javascript

# Serve all other Javascript files from their page directory.
- url: /static/(.*\.js)
  static_files: pages/\1
  upload: pages/(.*\.js)
  mime_type: text/javascript

# Serve tsv data files from their page directory.
- url: /static/(.*\.tsv)
  static_files: pages/\1
  upload: pages/(.*\.tsv)
  mime_type: text/tab-separated-values

# Static directory for all other static files.
- url: /static
  static_dir: static

# Make robots.txt accessible at the root URL.
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Find the favicon.
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

# Setup appstats on a custom path.
- url: /admin/stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

# Restrict access to the admin section of the website
- url: /admin/.*
  script: main.app
  login: admin

# Direct all remaining urls to the main app.
- url: .*
  script: main.app
