application: visi-bull
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers tell app engine how to route requests to your application.
handlers:

# Workaround for errors loading CSS.
- url: /static/css
  mime_type: text/css
  static_dir: static/css

# Static directory for all other static files.
- url: /static
  static_dir: static

# Make robots.txt accessible at the root URL.
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Find the favicon.
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

# Add the remote_api on a custom path.
- url: /admin/remote_api.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin

# Setup appstats on a custom path.
- url: /admin/stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

# Restrict access to the admin section of the website
- url: /admin/.*
  script: main.app
  login: admin

# Direct all remaining urls to the main app.
- url: .*
  script: main.app
